const Countries = [
  {country: 'Afghanistan', code: '93', iso: 'AF', flag: 'AF.png'},
  {country: 'Andorra', code: '376', iso: 'AD', flag: 'AD.png'},
  {country: 'United Arab Emirates', code: '971', iso: 'AE', flag: 'AE.png'},
  {country: 'Antigua and Barbuda', code: '1-268', iso: 'AG', flag: 'AG.png'},
  {country: 'Anguilla', code: '1-264', iso: 'AI', flag: 'AI.png'},
  {country: 'Albania', code: '355', iso: 'AL', flag: 'AL.png'},
  {country: 'Armenia', code: '374', iso: 'AM', flag: 'AM.png'},
  {country: 'Angola', code: '244', iso: 'AO', flag: 'AO.png'},
  {country: 'Argentina', code: '54', iso: 'AR', flag: 'AR.png'},
  {country: 'American Samoa', code: '1-684', iso: 'AS', flag: 'AS.png'},
  {country: 'Austria', code: '43', iso: 'AT', flag: 'AT.png'},
  {country: 'Australia', code: '61', iso: 'AU', flag: 'AU.png'},
  {country: 'Aruba', code: '297', iso: 'AW', flag: 'AW.png'},
  {country: 'Aland Islands', code: '358-18', iso: 'AX', flag: 'AX.png'},
  {country: 'Azerbaijan', code: '994', iso: 'AZ', flag: 'AZ.png'},
  {country: 'Bosnia and Herzegovina', code: '387', iso: 'BA', flag: 'BA.png'},
  {country: 'Barbados', code: '1-246', iso: 'BB', flag: 'BB.png'},
  {country: 'Bangladesh', code: '880', iso: 'BD', flag: 'BD.png'},
  {country: 'Belgium', code: '32', iso: 'BE', flag: 'BE.png'},
  {country: 'Burkina Faso', code: '226', iso: 'BF', flag: 'BF.png'},
  {country: 'Bulgaria', code: '359', iso: 'BG', flag: 'BG.png'},
  {country: 'Bahrain', code: '973', iso: 'BH', flag: 'BH.png'},
  {country: 'Burundi', code: '257', iso: 'BI', flag: 'BI.png'},
  {country: 'Benin', code: '229', iso: 'BJ', flag: 'BJ.png'},
  {country: 'Saint Barthélemy', code: '590', iso: 'BL', flag: 'BL.png'},
  {country: 'Bermuda', code: '1-441', iso: 'BM', flag: 'BM.png'},
  {country: 'Brunei Darussalam', code: '673', iso: 'BN', flag: 'BN.png'},
  {country: 'Bolivia', code: '591', iso: 'BO', flag: 'BO.png'},
  {country: 'Bonaire, Sint Eustatius and Saba', code: '599', iso: 'BQ', flag: 'BQ.png'},
  {country: 'Brazil', code: '55', iso: 'BR', flag: 'BR.png'},
  {country: 'Bahamas', code: '1-242', iso: 'BS', flag: 'BS.png'},
  {country: 'Bhutan', code: '975', iso: 'BT', flag: 'BT.png'},
  {country: 'Bouvet Island', code: '47', iso: 'BV', flag: 'BV.png'},
  {country: 'Botswana', code: '267', iso: 'BW', flag: 'BW.png'},
  {country: 'Belarus', code: '375', iso: 'BY', flag: 'BY.png'},
  {country: 'Belize', code: '501', iso: 'BZ', flag: 'BZ.png'},
  {country: 'Canada', code: '1', iso: 'CA', flag: 'CA.png'},
  {country: 'Cocos (Keeling) Islands', code: '61', iso: 'CC', flag: 'CC.png'},
  {country: 'Democratic Republic of the Congo', code: '243', iso: 'CD', flag: 'CD.png'},
  {country: 'Central African Republic', code: '236', iso: 'CF', flag: 'CF.png'},
  {country: 'Congo', code: '242', iso: 'CG', flag: 'CG.png'},
  {country: 'Switzerland', code: '41', iso: 'CH', flag: 'CH.png'},
  {country: 'Ivory Coast', code: '225', iso: 'CI', flag: 'CI.png'},
  {country: 'Cook Islands', code: '682', iso: 'CK', flag: 'CK.png'},
  {country: 'Chile', code: '56', iso: 'CL', flag: 'CL.png'},
  {country: 'Cameroon', code: '237', iso: 'CM', flag: 'CM.png'},
  {country: 'China', code: '86', iso: 'CN', flag: 'CN.png'},
  {country: 'Colombia', code: '57', iso: 'CO', flag: 'CO.png'},
  {country: 'Costa Rica', code: '506', iso: 'CR', flag: 'CR.png'},
  {country: 'Cuba', code: '53', iso: 'CU', flag: 'CU.png'},
  {country: 'Cape Verde', code: '238', iso: 'CV', flag: 'CV.png'},
  {country: 'Curaçao', code: '599', iso: 'CW', flag: 'CW.png'},
  {country: 'Christmas Island', code: '61', iso: 'CX', flag: 'CX.png'},
  {country: 'Cyprus', code: '357', iso: 'CY', flag: 'CY.png'},
  {country: 'Czech Republic', code: '420', iso: 'CZ', flag: 'CZ.png'},
  {country: 'Germany', code: '49', iso: 'DE', flag: 'DE.png'},
  {country: 'Djibouti', code: '253', iso: 'DJ', flag: 'DJ.png'},
  {country: 'Denmark', code: '45', iso: 'DK', flag: 'DK.png'},
  {country: 'Dominica', code: '1-767', iso: 'DM', flag: 'DM.png'},
  {country: 'Dominican Republic', code: '1-809, 1-829, 1-849', iso: 'DO', flag: 'DO.png'},
  {country: 'Algeria', code: '213', iso: 'DZ', flag: 'DZ.png'},
  {country: 'Ecuador', code: '593', iso: 'EC', flag: 'EC.png'},
  {country: 'Estonia', code: '372', iso: 'EE', flag: 'EE.png'},
  {country: 'Egypt', code: '20', iso: 'EG', flag: 'EG.png'},
  {country: 'Western Sahara', code: '212', iso: 'EH', flag: 'EH.png'},
  {country: 'Eritrea', code: '291', iso: 'ER', flag: 'ER.png'},
  {country: 'Spain', code: '34', iso: 'ES', flag: 'ES.png'},
  {country: 'Ethiopia', code: '251', iso: 'ET', flag: 'ET.png'},
  {country: 'Finland', code: '358', iso: 'FI', flag: 'FI.png'},
  {country: 'Fiji', code: '679', iso: 'FJ', flag: 'FJ.png'},
  {country: 'Falkland Islands (Malvinas)', code: '500', iso: 'FK', flag: 'FK.png'},
  {country: 'Micronesia', code: '691', iso: 'FM', flag: 'FM.png'},
  {country: 'Faroe Islands', code: '298', iso: 'FO', flag: 'FO.png'},
  {country: 'France', code: '33', iso: 'FR', flag: 'FR.png'},
  {country: 'Gabon', code: '241', iso: 'GA', flag: 'GA.png'},
  {country: 'United Kingdom (England)', code: '44', iso: 'GB-ENG', flag: 'GB-ENG.png'},
  {country: 'United Kingdom (Northern Ireland)', code: '44', iso: 'GB-NIR', flag: 'GB-NIR.png'},
  {country: 'United Kingdom (Scotland)', code: '44', iso: 'GB-SCT', flag: 'GB-SCT.png'},
  {country: 'United Kingdom (Wales)', code: '44', iso: 'GB-WLS', flag: 'GB-WLS.png'},
  {country: 'United Kingdom', code: '44', iso: 'GB', flag: 'GB.png'},
  {country: 'Grenada', code: '1-473', iso: 'GD', flag: 'GD.png'},
  {country: 'Georgia', code: '995', iso: 'GE', flag: 'GE.png'},
  {country: 'French Guiana', code: '594', iso: 'GF', flag: 'GF.png'},
  {country: 'Guernsey', code: '44-1481', iso: 'GG', flag: 'GG.png'},
  {country: 'Ghana', code: '233', iso: 'GH', flag: 'GH.png'},
  {country: 'Gibraltar', code: '350', iso: 'GI', flag: 'GI.png'},
  {country: 'Greenland', code: '299', iso: 'GL', flag: 'GL.png'},
  {country: 'Gambia', code: '220', iso: 'GM', flag: 'GM.png'},
  {country: 'Guinea', code: '224', iso: 'GN', flag: 'GN.png'},
  {country: 'Guadeloupe', code: '590', iso: 'GP', flag: 'GP.png'},
  {country: 'Equatorial Guinea', code: '240', iso: 'GQ', flag: 'GQ.png'},
  {country: 'Greece', code: '30', iso: 'GR', flag: 'GR.png'},
  {country: 'South Georgia and the South Sandwich Islands', code: '500', iso: 'GS', flag: 'GS.png'},
  {country: 'Guatemala', code: '502', iso: 'GT', flag: 'GT.png'},
  {country: 'Guam', code: '1-671', iso: 'GU', flag: 'GU.png'},
  {country: 'Guinea-Bissau', code: '245', iso: 'GW', flag: 'GW.png'},
  {country: 'Guyana', code: '592', iso: 'GY', flag: 'GY.png'},
  {country: 'Hong Kong', code: '852', iso: 'HK', flag: 'HK.png'},
  {country: 'Heard Island and McDonald Islands', code: '500', iso: 'HM', flag: 'HM.png'},
  {country: 'Honduras', code: '504', iso: 'HN', flag: 'HN.png'},
  {country: 'Croatia', code: '385', iso: 'HR', flag: 'HR.png'},
  {country: 'Haiti', code: '509', iso: 'HT', flag: 'HT.png'},
  {country: 'Hungary', code: '36', iso: 'HU', flag: 'HU.png'},
  {country: 'Indonesia', code: '62', iso: 'ID', flag: 'ID.png'},
  {country: 'Ireland', code: '353', iso: 'IE', flag: 'IE.png'},
  {country: 'Israel', code: '972', iso: 'IL', flag: 'IL.png'},
  {country: 'Isle of Man', code: '44-1624', iso: 'IM', flag: 'IM.png'},
  {country: 'India', code: '91', iso: 'IN', flag: 'IN.png'},
  {country: 'British Indian Ocean Territory', code: '246', iso: 'IO', flag: 'IO.png'},
  {country: 'Iraq', code: '964', iso: 'IQ', flag: 'IQ.png'},
  {country: 'Iran', code: '98', iso: 'IR', flag: 'IR.png'},
  {country: 'Iceland', code: '354', iso: 'IS', flag: 'IS.png'},
  {country: 'Italy', code: '39', iso: 'IT', flag: 'IT.png'},
  {country: 'Jersey', code: '44-1534', iso: 'JE', flag: 'JE.png'},
  {country: 'Jamaica', code: '1-876', iso: 'JM', flag: 'JM.png'},
  {country: 'Jordan', code: '962', iso: 'JO', flag: 'JO.png'},
  {country: 'Japan', code: '81', iso: 'JP', flag: 'JP.png'},
  {country: 'Kenya', code: '254', iso: 'KE', flag: 'KE.png'},
  {country: 'Kyrgyzstan', code: '996', iso: 'KG', flag: 'KG.png'},
  {country: 'Cambodia', code: '855', iso: 'KH', flag: 'KH.png'},
  {country: 'Kiribati', code: '686', iso: 'KI', flag: 'KI.png'},
  {country: 'Comoros', code: '269', iso: 'KM', flag: 'KM.png'},
  {country: 'Saint Kitts and Nevis', code: '1-869', iso: 'KN', flag: 'KN.png'},
  {country: 'North Korea', code: '850', iso: 'KP', flag: 'KP.png'},
  {country: 'South Korea', code: '82', iso: 'KR', flag: 'KR.png'},
  {country: 'Kuwait', code: '965', iso: 'KW', flag: 'KW.png'},
  {country: 'Cayman Islands', code: '1-345', iso: 'KY', flag: 'KY.png'},
  {country: 'Kazakhstan', code: '7', iso: 'KZ', flag: 'KZ.png'},
  {country: 'Laos', code: '856', iso: 'LA', flag: 'LA.png'},
  {country: 'Lebanon', code: '961', iso: 'LB', flag: 'LB.png'},
  {country: 'Saint Lucia', code: '1-758', iso: 'LC', flag: 'LC.png'},
  {country: 'Liechtenstein', code: '423', iso: 'LI', flag: 'LI.png'},
  {country: 'Sri Lanka', code: '94', iso: 'LK', flag: 'LK.png'},
  {country: 'Liberia', code: '231', iso: 'LR', flag: 'LR.png'},
  {country: 'Lesotho', code: '266', iso: 'LS', flag: 'LS.png'},
  {country: 'Lithuania', code: '370', iso: 'LT', flag: 'LT.png'},
  {country: 'Luxembourg', code: '352', iso: 'LU', flag: 'LU.png'},
  {country: 'Latvia', code: '371', iso: 'LV', flag: 'LV.png'},
  {country: 'Libya', code: '218', iso: 'LY', flag: 'LY.png'},
  {country: 'Morocco', code: '212', iso: 'MA', flag: 'MA.png'},
  {country: 'Monaco', code: '377', iso: 'MC', flag: 'MC.png'},
  {country: 'Moldova', code: '373', iso: 'MD', flag: 'MD.png'},
  {country: 'Montenegro', code: '382', iso: 'ME', flag: 'ME.png'},
  {country: 'Saint Martin', code: '590', iso: 'MF', flag: 'MF.png'},
  {country: 'Madagascar', code: '261', iso: 'MG', flag: 'MG.png'},
  {country: 'Marshall Islands', code: '692', iso: 'MH', flag: 'MH.png'},
  {country: 'North Macedonia', code: '389', iso: 'MK', flag: 'MK.png'},
  {country: 'Mali', code: '223', iso: 'ML', flag: 'ML.png'},
  {country: 'Myanmar', code: '95', iso: 'MM', flag: 'MM.png'},
  {country: 'Mongolia', code: '976', iso: 'MN', flag: 'MN.png'},
  {country: 'Macau', code: '853', iso: 'MO', flag: 'MO.png'},
  {country: 'Northern Mariana Islands', code: '1-670', iso: 'MP', flag: 'MP.png'},
  {country: 'Martinique', code: '596', iso: 'MQ', flag: 'MQ.png'},
  {country: 'Mauritania', code: '222', iso: 'MR', flag: 'MR.png'},
  {country: 'Montserrat', code: '1-664', iso: 'MS', flag: 'MS.png'},
  {country: 'Malta', code: '356', iso: 'MT', flag: 'MT.png'},
  {country: 'Mauritius', code: '230', iso: 'MU', flag: 'MU.png'},
  {country: 'Maldives', code: '960', iso: 'MV', flag: 'MV.png'},
  {country: 'Malawi', code: '265', iso: 'MW', flag: 'MW.png'},
  {country: 'Mexico', code: '52', iso: 'MX', flag: 'MX.png'},
  {country: 'Malaysia', code: '60', iso: 'MY', flag: 'MY.png'},
  {country: 'Mozambique', code: '258', iso: 'MZ', flag: 'MZ.png'},
  {country: 'Namibia', code: '264', iso: 'NA', flag: 'NA.png'},
  {country: 'New Caledonia', code: '687', iso: 'NC', flag: 'NC.png'},
  {country: 'Niger', code: '227', iso: 'NE', flag: 'NE.png'},
  {country: 'Norfolk Island', code: '672', iso: 'NF', flag: 'NF.png'},
  {country: 'Nigeria', code: '234', iso: 'NG', flag: 'NG.png'},
  {country: 'Nicaragua', code: '505', iso: 'NI', flag: 'NI.png'},
  {country: 'Netherlands', code: '31', iso: 'NL', flag: 'NL.png'},
  {country: 'Norway', code: '47', iso: 'NO', flag: 'NO.png'},
  {country: 'Nepal', code: '977', iso: 'NP', flag: 'NP.png'},
  {country: 'Nauru', code: '674', iso: 'NR', flag: 'NR.png'},
  {country: 'Niue', code: '683', iso: 'NU', flag: 'NU.png'},
  {country: 'New Zealand', code: '64', iso: 'NZ', flag: 'NZ.png'},
  {country: 'Oman', code: '968', iso: 'OM', flag: 'OM.png'},
  {country: 'Panama', code: '507', iso: 'PA', flag: 'PA.png'},
  {country: 'Peru', code: '51', iso: 'PE', flag: 'PE.png'},
  {country: 'French Polynesia', code: '689', iso: 'PF', flag: 'PF.png'},
  {country: 'Papua New Guinea', code: '675', iso: 'PG', flag: 'PG.png'},
  {country: 'Philippines', code: '63', iso: 'PH', flag: 'PH.png'},
  {country: 'Pakistan', code: '92', iso: 'PK', flag: 'PK.png'},
  {country: 'Poland', code: '48', iso: 'PL', flag: 'PL.png'},
  {country: 'Saint Pierre and Miquelon', code: '508', iso: 'PM', flag: 'PM.png'},
  {country: 'Pitcairn', code: '64', iso: 'PN', flag: 'PN.png'},
  {country: 'Puerto Rico', code: '1-787, 1-939', iso: 'PR', flag: 'PR.png'},
  {country: 'Palestine', code: '970', iso: 'PS', flag: 'PS.png'},
  {country: 'Portugal', code: '351', iso: 'PT', flag: 'PT.png'},
  {country: 'Palau', code: '680', iso: 'PW', flag: 'PW.png'},
  {country: 'Paraguay', code: '595', iso: 'PY', flag: 'PY.png'},
  {country: 'Qatar', code: '974', iso: 'QA', flag: 'QA.png'},
  {country: 'Réunion', code: '262', iso: 'RE', flag: 'RE.png'},
  {country: 'Romania', code: '40', iso: 'RO', flag: 'RO.png'},
  {country: 'Serbia', code: '381', iso: 'RS', flag: 'RS.png'},
  {country: 'Russia', code: '7', iso: 'RU', flag: 'RU.png'},
  {country: 'Rwanda', code: '250', iso: 'RW', flag: 'RW.png'},
  {country: 'Saudi Arabia', code: '966', iso: 'SA', flag: 'SA.png'},
  {country: 'Solomon Islands', code: '677', iso: 'SB', flag: 'SB.png'},
  {country: 'Seychelles', code: '248', iso: 'SC', flag: 'SC.png'},
  {country: 'Sudan', code: '249', iso: 'SD', flag: 'SD.png'},
  {country: 'Sweden', code: '46', iso: 'SE', flag: 'SE.png'},
  {country: 'Singapore', code: '65', iso: 'SG', flag: 'SG.png'},
  {country: 'Saint Helena', code: '290', iso: 'SH', flag: 'SH.png'},
  {country: 'Slovenia', code: '386', iso: 'SI', flag: 'SI.png'},
  {country: 'Svalbard and Jan Mayen', code: '47', iso: 'SJ', flag: 'SJ.png'},
  {country: 'Slovakia', code: '421', iso: 'SK', flag: 'SK.png'},
  {country: 'Sierra Leone', code: '232', iso: 'SL', flag: 'SL.png'},
  {country: 'San Marino', code: '378', iso: 'SM', flag: 'SM.png'},
  {country: 'Senegal', code: '221', iso: 'SN', flag: 'SN.png'},
  {country: 'Somalia', code: '252', iso: 'SO', flag: 'SO.png'},
  {country: 'Suriname', code: '597', iso: 'SR', flag: 'SR.png'},
  {country: 'South Sudan', code: '211', iso: 'SS', flag: 'SS.png'},
  {country: 'São Tomé and Príncipe', code: '239', iso: 'ST', flag: 'ST.png'},
  {country: 'El Salvador', code: '503', iso: 'SV', flag: 'SV.png'},
  {country: 'Sint Maarten', code: '1-721', iso: 'SX', flag: 'SX.png'},
  {country: 'Syria', code: '963', iso: 'SY', flag: 'SY.png'},
  {country: 'Eswatini', code: '268', iso: 'SZ', flag: 'SZ.png'},
  {country: 'Turks and Caicos Islands', code: '1-649', iso: 'TC', flag: 'TC.png'},
  {country: 'Chad', code: '235', iso: 'TD', flag: 'TD.png'},
  {country: 'French Southern Territories', code: '262', iso: 'TF', flag: 'TF.png'},
  {country: 'Togo', code: '228', iso: 'TG', flag: 'TG.png'},
  {country: 'Thailand', code: '66', iso: 'TH', flag: 'TH.png'},
  {country: 'Tajikistan', code: '992', iso: 'TJ', flag: 'TJ.png'},
  {country: 'Tokelau', code: '690', iso: 'TK', flag: 'TK.png'},
  {country: 'Timor-Leste', code: '670', iso: 'TL', flag: 'TL.png'},
  {country: 'Turkmenistan', code: '993', iso: 'TM', flag: 'TM.png'},
  {country: 'Tunisia', code: '216', iso: 'TN', flag: 'TN.png'},
  {country: 'Tonga', code: '676', iso: 'TO', flag: 'TO.png'},
  {country: 'Turkey', code: '90', iso: 'TR', flag: 'TR.png'},
  {country: 'Trinidad and Tobago', code: '1-868', iso: 'TT', flag: 'TT.png'},
  {country: 'Tuvalu', code: '688', iso: 'TV', flag: 'TV.png'},
  {country: 'Taiwan', code: '886', iso: 'TW', flag: 'TW.png'},
  {country: 'Tanzania', code: '255', iso: 'TZ', flag: 'TZ.png'},
  {country: 'Ukraine', code: '380', iso: 'UA', flag: 'UA.png'},
  {country: 'Uganda', code: '256', iso: 'UG', flag: 'UG.png'},
  {country: 'United States Minor Outlying Islands', code: '1', iso: 'UM', flag: 'UM.png'},
  {country: 'United States', code: '1', iso: 'US', flag: 'US.png'},
  {country: 'Uruguay', code: '598', iso: 'UY', flag: 'UY.png'},
  {country: 'Uzbekistan', code: '998', iso: 'UZ', flag: 'UZ.png'},
  {country: 'Vatican City', code: '379', iso: 'VA', flag: 'VA.png'},
  {country: 'Saint Vincent and the Grenadines', code: '1-784', iso: 'VC', flag: 'VC.png'},
  {country: 'Venezuela', code: '58', iso: 'VE', flag: 'VE.png'},
  {country: 'British Virgin Islands', code: '1-284', iso: 'VG', flag: 'VG.png'},
  {country: 'U.S. Virgin Islands', code: '1-340', iso: 'VI', flag: 'VI.png'},
  {country: 'Vietnam', code: '84', iso: 'VN', flag: 'VN.png'},
  {country: 'Vanuatu', code: '678', iso: 'VU', flag: 'VU.png'},
  {country: 'Wallis and Futuna', code: '681', iso: 'WF', flag: 'WF.png'},
  {country: 'Samoa', code: '685', iso: 'WS', flag: 'WS.png'},
  {country: 'Kosovo', code: '383', iso: 'XK', flag: 'XK.png'},
  {country: 'Yemen', code: '967', iso: 'YE', flag: 'YE.png'},
  {country: 'Mayotte', code: '262', iso: 'YT', flag: 'YT.png'},
  {country: 'South Africa', code: '27', iso: 'ZA', flag: 'ZA.png'},
  {country: 'Zambia', code: '260', iso: 'ZM', flag: 'ZM.png'},
  {country: 'Zimbabwe', code: '263', iso: 'ZW', flag: 'ZW.png'}

];
